### PR TITLE
use zk client connection timeout

### PR DESCRIPTION
**Pull request by camallen**
avoid Timeout in sidekiq, http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/

### CODE REVIEW

**Comment by camallen** [comment]
@parrish I been playing around testing the node set without the timeout since this may cause problems using the client in the background. I can't figure out how to get the ZK lib to abort early (default does timeout though), I'm wondering if you'd support a client connection that doesn't use the timeout option by default or configurable. I'm also starting to wonder why the client node_set uses celluloid actor paradigm as well.

**Comment by parrish** [comment]
So apparently, the ZK client has a number of [subclassed strategies available](https://github.com/zk-ruby/zk/tree/master/lib/zk/client) and the default client disregards the `timeout` connection option.

We could switch to the [threaded client](https://github.com/zk-ruby/zk/blob/master/lib/zk/client/threaded.rb) to get a timeout with something like:

``` ruby
module Cellect
  class NodeSet
    # ...
    class NotConnectedError < StandardError; end

    def initialize_zk
      # don't let ZK hang the thread, just retry connection on restart
      self.zk = ZK::Client::Threaded.new zk_url, timeout: 5, chroot: '/cellect'
      raise NotConnectedError.new('Could not connect to ZooKeeper') unless zk.connected?
      setup
      self.state = :ready
    end

    # ...
```

That said, the specs will pass with the threaded client, but I'm not completely sure what other implications that switch would have.

**Comment by camallen** [comment]
Pretty sure the threaded client was what i was getting by default, https://github.com/zk-ruby/zk/blob/master/lib/zk/client.rb#L28. the opts were making it into the client in my testing the behavior was not expected though (when there was no ZK server). 

We can use docker-compose to get this into testing and a rails console.

**Comment by parrish** [comment]
Yeah, I haven't tried to walk that inheritance chain, but `ZK.new` and `ZK::Client.new` are not the same.

`ZK.new 'localhost:21811', timeout: 0.1, chroot: '/cellect'` will hang for a long time

`ZK::Client.new 'localhost:21811', timeout: 0.1, chroot: '/cellect'` will work correctly.

**Comment by camallen** [comment]
Right - i'll have a look at that.

**Comment by camallen** [comment]
updated to use the single threaded client with a timeout. I've reworked the specs setup as well to use a zk-server gem.

**Comment by parrish** [comment]
Awesome!

**Comment by parrish** [comment]
Just cut release 1.0

**Comment by parrish** [comment]
So, 0.5 seconds is apparently way to aggressive for Zookeeper.  I moved the default back to 5 seconds, but it's configurable now with the `ZK_TIMEOUT` env variable.

Re-released at 1.0.1

**Comment by camallen** [comment]
Good catch, i should have made it configurable in the PR. will test it out today.

**Pull request merged**
