### PR TITLE
Add travis.yml file

### PR DESCRIPTION
**Pull request by edpaget**

### CODE REVIEW

**Comment by parrish** [comment]
Looks like this is failing with

`random_set.h:8:45: fatal error: boost/random/mersenne_twister.hpp: No such file or directory`

Not sure why it's not finding libboost correctly...

**Comment by edpaget** [comment]
It looks like it's installing a slightly older version of Boost.

**Comment by edpaget** [comment]
Whoo! Mostly working now. @parrish I always see these same failures when I run Cellect locally when a zookeeper started independently of the test suite. Is there anything special your start zookeeper script does that might prevent these errors?

**Comment by parrish** [comment]
5a4f64627 should fix the timeout errors (I wasn't resetting the ZK url correctly)
Other than that, just make sure you've got a clear ZK data directory before the test runs -- the specs expect to be able to predict the auto-incremented ids

**Comment by edpaget** [comment]
Sweet it's all working I'm going to merge it in.

**Pull request merged**
