### PR TITLE
Update for ruby 2.2.0

### PR DESCRIPTION
**Pull request by edpaget**
* Update zk gem
* Remove circular argument references

I'd like to get this in so I can start testing Panoptes on JRuby 9.0.0.0, which should offer several performance improvements.

### CODE REVIEW

**Comment by edpaget** [comment]
This is dependent on parrish/diff_set#1

**Comment by edpaget** [comment]
I'll check in a Gemfile.lock when the above PR is dealt with. I have it pointing to my git repo of diff_set at the moment.

**Comment by parrish** [comment]
I just released 0.1.0 with these changes

**Comment by edpaget** [comment]
Thanks a bunch.

**Pull request closed without merging**
